# Generated by Django 4.2.7 on 2024-04-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranslationModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("original_text", models.CharField(max_length=255)),
                ("hindi_translation", models.CharField(max_length=255)),
                ("urdu_translation", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PhoneticConversionModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("original_text", models.CharField(max_length=255)),
                ("original_phonetic", models.CharField(max_length=255)),
                ("hindi_phonetic", models.CharField(max_length=255)),
                ("urdu_phonetic", models.CharField(max_length=255)),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phoneticapp.translationmodel",
                    ),
                ),
            ],
        ),
    ]
