# Generated by Django 4.2.7 on 2024-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phoneticapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("original_text", models.CharField(max_length=255)),
                ("hindi_translation", models.CharField(max_length=255)),
                ("urdu_translation", models.CharField(max_length=255)),
                ("original_phonetic", models.CharField(max_length=255)),
                ("hindi_phonetic", models.CharField(max_length=255)),
                ("urdu_phonetic", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="PhoneticConversionModel",
        ),
        migrations.DeleteModel(
            name="TranslationModel",
        ),
    ]
