# Generated by Django 4.2.7 on 2024-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phoneticapp", "0002_translation_delete_phoneticconversionmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="nepali_phonetic",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="translation",
            name="nepali_translation",
            field=models.CharField(default="", max_length=255),
        ),
    ]
