# Generated by Django 4.2.7 on 2024-05-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phoneticapp", "0003_translation_nepali_phonetic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="telgu_phonetic",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="translation",
            name="telugu_translation",
            field=models.CharField(default="", max_length=255),
        ),
    ]
