# Generated by Django 4.2.7 on 2024-05-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phoneticapp", "0004_translation_telgu_phonetic_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="translation",
            old_name="telgu_phonetic",
            new_name="telegu_phonetic",
        ),
    ]
