# Generated by Django 4.2.7 on 2024-05-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phoneticapp", "0005_rename_telgu_phonetic_translation_telegu_phonetic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="translation",
            old_name="telegu_phonetic",
            new_name="telugu_phonetic",
        ),
    ]
